// API
export const API_REQUEST = 'API_REQUEST'

// Global
export const SOCKET_LOGIN_SUCCESS = 'SOCKET_LOGIN_SUCCESS'

// Auth
export const LOGIN_START = 'LOGIN_START'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGOUT = 'LOGOUT'

// Messages
export const SET_MESSAGES = 'SET_MESSAGES'
export const SEND_MESSAGE = 'SEND_MESSAGE'
export const ADD_MESSAGE = 'ADD_MESSAGE'
export const FETCH_MESSAGES_START = 'FETCH_MESSAGES_START'
export const FETCH_MESSAGES_SUCCESS = 'FETCH_MESSAGES_SUCCESS'
export const FETCH_MESSAGES_FAIL = 'FETCH_MESSAGES_FAIL'

// Tree
export const SET_TREE = 'SET_TREE'
export const UPDATE_TREE = 'UPDATE_TREE'
export const SET_FILTERED_TREE = 'SET_FILTERED_TREE'
export const SET_EXPANDED_IDS = 'SET_EXPANDED_IDS'
export const SET_ACTIVE = 'SET_ACTIVE'
export const SET_TREE_ITEMS_TYPE = 'SET_TREE_ITEMS_TYPE'
