// API
export const API_REQUEST = 'API_REQUEST'

// Global
export const SOCKET_LOGIN_SUCCESS = 'SOCKET_LOGIN_SUCCESS'

// Auth
export const LOGIN_START = 'LOGIN_START'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGOUT = 'LOGOUT'

// Messages
export const SET_MESSAGES = 'SET_MESSAGES'
export const SEND_MESSAGE = 'SEND_MESSAGE'
export const ADD_MESSAGE = 'ADD_MESSAGE'
export const FETCH_MESSAGES_START = 'FETCH_MESSAGES_START'
export const FETCH_MESSAGES_SUCCESS = 'FETCH_MESSAGES_SUCCESS'
export const FETCH_MESSAGES_FAIL = 'FETCH_MESSAGES_FAIL'

// Tree
export const FETCH_GROUPS_SUCCESS = 'FETCH_GROUPS_SUCCESS'
export const SET_GROUPS = 'SET_GROUPS'
export const SET_ACTIVE_GROUP_ID = 'SET_ACTIVE_GROUP_ID'
export const SET_SHOWN_GROUPS = 'SET_SHOWN_GROUPS'
export const SET_FILTERED_GROUPS = 'SET_FILTERED_GROUPS'
export const KEY_EVENT_ON_TREE = 'KEY_EVENT_ON_TREE'
export const EXPAND_GROUP = 'EXPAND_GROUP'
export const FOLD_GROUP = 'FOLD_GROUP'
